### ISSUE TITLE
Enable support for WebP imge format

### ISSUE THREAD

**Issue by brendan-ward** [consbio/ncdjango#2]
Pillow supports [WebP](http://pillow.readthedocs.org/en/3.0.x/handbook/image-file-formats.html?highlight=optimize#webp).

Will need to experiment with lossless or quality.  I've tried with other tools that use 90% quality and see a decrease in file size, and no visual difference.

This can be returned if the request header includes `image/webp` as a supported type, even if the request is for PNG.

**Comment by brendan-ward** [comment]
I found these settings worked pretty well for clover: 

```
    kwargs = {}
    if format == 'png':
        kwargs['optimize'] = True
    elif format == 'jpg':
        img = img.convert('RGB')
        kwargs['progressive'] = True
    elif format == 'webp':
        img = img.convert('RGBA')
        kwargs['lossless'] = True

    img.save(filename, **kwargs)
```

**Comment by nikmolnar** [comment]
Are the conversions necessary?

**Comment by brendan-ward** [comment]
Yes, otherwise you get errors.  Neither format supports palettes.  JPG doesn't support alpha.

**Comment by nikmolnar** [comment]
Ok. I thought the conversion would be implicit on save. I guess not.
