### ISSUE TITLE
Conditionally return JPEG, if possible

### ISSUE THREAD

**Issue by brendan-ward** [consbio/ncdjango#3]
Basic tests of regions fully covered by data pixels (no NODATA) result in JPGs that are somewhat to quite a bit smaller than the default PNG24, with no noticeable encoding artifacts.

This only works if there are no NODATA pixels within the warped area.  While this is easy in numpy arrays, this may be harder to determine efficiently for images.  If you have an alpha channel, it could be possible to look for values in there that indicate NODATA.

**Comment by nikmolnar** [comment]
I think if we should present this as an extra option in the ArcGIS (Extended) API (the interface that  supports extra functionality like styling). Otherwise, it feels like bad form to return JPEG images to a client that specifically requested another format.

**Comment by nikmolnar** [comment]
What's the decrease compared PNG8?

**Comment by brendan-ward** [comment]
Don't know, since that type wasn't supported when I did my tests.  Well worth testing.  For an arbitrary area that included about 20 data pixels on edge prior to reprojection, and across a fairly large range in values, I saw an output file size of 1/3 the size compared to PNG (24?) for the same footprint.

Good point about extended API instead of core API.  Maybe an additional format type in addition to the standard ones?  E.g., `smallest` instead of `png8`?  Or were you thinking a new query parameter?

**Comment by brendan-ward** [comment]
Testing in clover w/ PNG8 produces a PNG smaller than JPG at default quality (42% of size of JPG).  So PNG8 is likely to be better than JPG in this case.

**Comment by brendan-ward** [comment]
And in this specific case, PNG24 was smaller too, by just a little.

**Comment by brendan-ward** [comment]
I'm actually now rethinking this request, seeing how it works out on some test map data.  Compared to PNG8s, file sizes are larger in JPG, and there are quite noticeable artifacts.  Let's stick to higher quality formats for now, except when JPG is actually requested.

Would require some tuning to get the most of out JPG in this usage.
