### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by nikmolnar** [consbio/ncdjango#5]
There is at least one issue currently with Django 1.9. In `urls.py`, there is an import for `from django.utils.importlib import import_module` which is no longer valid and should be replaced with `from importlib import import_module`.

**Comment by TaylorMutch** [comment]
@nikmolnar This looks to be resolved with Django 1.11 support.

**Comment by nikmolnar** [comment]
Yes, thanks for the reminder!
